# Generated by Django 3.2.18 on 2024-01-07 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_recipe_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
